# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'panel.ui'
#
# Created: Fri Oct 30 18:00:09 2015
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(905, 532)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.pushButton_abort = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_abort.setObjectName("pushButton_abort")
        self.horizontalLayout_7.addWidget(self.pushButton_abort)
        self.pushButton_apply = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_apply.setObjectName("pushButton_apply")
        self.horizontalLayout_7.addWidget(self.pushButton_apply)
        self.pushButton_ok = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_7.addWidget(self.pushButton_ok)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_selectApps = QtWidgets.QWidget()
        self.tab_selectApps.setObjectName("tab_selectApps")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_selectApps)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 653, 247))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.line_2 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_8.addWidget(self.line_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_availableApps = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_availableApps.setFont(font)
        self.label_availableApps.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_availableApps.setAlignment(QtCore.Qt.AlignCenter)
        self.label_availableApps.setObjectName("label_availableApps")
        self.verticalLayout.addWidget(self.label_availableApps)
        self.checkBox_symboler = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_symboler.setObjectName("checkBox_symboler")
        self.verticalLayout.addWidget(self.checkBox_symboler)
        self.checkBox_movie = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_movie.setObjectName("checkBox_movie")
        self.verticalLayout.addWidget(self.checkBox_movie)
        self.checkBox_audio = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_audio.setObjectName("checkBox_audio")
        self.verticalLayout.addWidget(self.checkBox_audio)
        self.checkBox_viewer = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_viewer.setObjectName("checkBox_viewer")
        self.verticalLayout.addWidget(self.checkBox_viewer)
        self.checkBox_speller = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_speller.setObjectName("checkBox_speller")
        self.verticalLayout.addWidget(self.checkBox_speller)
        self.checkBox_email = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_email.setObjectName("checkBox_email")
        self.verticalLayout.addWidget(self.checkBox_email)
        self.checkBox_paint = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_paint.setObjectName("checkBox_paint")
        self.verticalLayout.addWidget(self.checkBox_paint)
        self.checkBox_blog = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_blog.setObjectName("checkBox_blog")
        self.verticalLayout.addWidget(self.checkBox_blog)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab_selectApps, "")
        self.tab_generalSettings = QtWidgets.QWidget()
        self.tab_generalSettings.setObjectName("tab_generalSettings")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_generalSettings)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line = QtWidgets.QFrame(self.tab_generalSettings)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.comboBox_input = QtWidgets.QComboBox(self.tab_generalSettings)
        self.comboBox_input.setObjectName("comboBox_input")
        self.comboBox_input.addItem("")
        self.comboBox_input.addItem("")
        self.comboBox_input.addItem("")
        self.comboBox_input.addItem("")
        self.comboBox_input.addItem("")
        self.comboBox_input.addItem("")
        self.comboBox_input.addItem("")
        self.comboBox_input.addItem("")
        self.comboBox_input.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.comboBox_input)
        self.label_input = QtWidgets.QLabel(self.tab_generalSettings)
        self.label_input.setObjectName("label_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_input)
        self.comboBox_skin = QtWidgets.QComboBox(self.tab_generalSettings)
        self.comboBox_skin.setEditable(False)
        self.comboBox_skin.setObjectName("comboBox_skin")
        self.comboBox_skin.addItem("")
        self.comboBox_skin.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.comboBox_skin)
        self.label_skin = QtWidgets.QLabel(self.tab_generalSettings)
        self.label_skin.setObjectName("label_skin")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_skin)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalSlider_volume = QtWidgets.QSlider(self.tab_generalSettings)
        self.horizontalSlider_volume.setMaximum(100)
        self.horizontalSlider_volume.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_volume.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_volume.setTickInterval(10)
        self.horizontalSlider_volume.setObjectName("horizontalSlider_volume")
        self.horizontalLayout.addWidget(self.horizontalSlider_volume)
        self.label_volumeCounter = QtWidgets.QLabel(self.tab_generalSettings)
        self.label_volumeCounter.setObjectName("label_volumeCounter")
        self.horizontalLayout.addWidget(self.label_volumeCounter)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout)
        self.label_volume = QtWidgets.QLabel(self.tab_generalSettings)
        self.label_volume.setObjectName("label_volume")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_volume)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalSlider_spriteTimeout = QtWidgets.QSlider(self.tab_generalSettings)
        self.horizontalSlider_spriteTimeout.setMinimum(500)
        self.horizontalSlider_spriteTimeout.setMaximum(5000)
        self.horizontalSlider_spriteTimeout.setSingleStep(500)
        self.horizontalSlider_spriteTimeout.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_spriteTimeout.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_spriteTimeout.setTickInterval(500)
        self.horizontalSlider_spriteTimeout.setObjectName("horizontalSlider_spriteTimeout")
        self.horizontalLayout_2.addWidget(self.horizontalSlider_spriteTimeout)
        self.label_spriteTimeoutCounter = QtWidgets.QLabel(self.tab_generalSettings)
        self.label_spriteTimeoutCounter.setObjectName("label_spriteTimeoutCounter")
        self.horizontalLayout_2.addWidget(self.label_spriteTimeoutCounter)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_2)
        self.label_spriteTimeout = QtWidgets.QLabel(self.tab_generalSettings)
        self.label_spriteTimeout.setObjectName("label_spriteTimeout")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.label_spriteTimeout)
        self.comboBox_selectSound = QtWidgets.QComboBox(self.tab_generalSettings)
        self.comboBox_selectSound.setEditable(True)
        self.comboBox_selectSound.setObjectName("comboBox_selectSound")
        self.comboBox_selectSound.addItem("")
        self.comboBox_selectSound.setItemText(0, "")
        self.comboBox_selectSound.addItem("")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.comboBox_selectSound)
        self.label_selectSound = QtWidgets.QLabel(self.tab_generalSettings)
        self.label_selectSound.setObjectName("label_selectSound")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.label_selectSound)
        self.checkBox_sounds = QtWidgets.QCheckBox(self.tab_generalSettings)
        self.checkBox_sounds.setObjectName("checkBox_sounds")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.checkBox_sounds)
        self.checkBox_buttonSoundSupport = QtWidgets.QCheckBox(self.tab_generalSettings)
        self.checkBox_buttonSoundSupport.setObjectName("checkBox_buttonSoundSupport")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.checkBox_buttonSoundSupport)
        self.checkBox_textCase = QtWidgets.QCheckBox(self.tab_generalSettings)
        self.checkBox_textCase.setObjectName("checkBox_textCase")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.checkBox_textCase)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.line_8 = QtWidgets.QFrame(self.tab_generalSettings)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_3.addWidget(self.line_8)
        self.label_prediction = QtWidgets.QLabel(self.tab_generalSettings)
        self.label_prediction.setObjectName("label_prediction")
        self.verticalLayout_3.addWidget(self.label_prediction)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lineEdit_prediction7 = QtWidgets.QLineEdit(self.tab_generalSettings)
        self.lineEdit_prediction7.setObjectName("lineEdit_prediction7")
        self.horizontalLayout_12.addWidget(self.lineEdit_prediction7)
        self.lineEdit_prediction1 = QtWidgets.QLineEdit(self.tab_generalSettings)
        self.lineEdit_prediction1.setObjectName("lineEdit_prediction1")
        self.horizontalLayout_12.addWidget(self.lineEdit_prediction1)
        self.lineEdit_prediction8 = QtWidgets.QLineEdit(self.tab_generalSettings)
        self.lineEdit_prediction8.setObjectName("lineEdit_prediction8")
        self.horizontalLayout_12.addWidget(self.lineEdit_prediction8)
        self.lineEdit_prediction2 = QtWidgets.QLineEdit(self.tab_generalSettings)
        self.lineEdit_prediction2.setObjectName("lineEdit_prediction2")
        self.horizontalLayout_12.addWidget(self.lineEdit_prediction2)
        self.lineEdit_prediction3 = QtWidgets.QLineEdit(self.tab_generalSettings)
        self.lineEdit_prediction3.setObjectName("lineEdit_prediction3")
        self.horizontalLayout_12.addWidget(self.lineEdit_prediction3)
        self.lineEdit_prediction4 = QtWidgets.QLineEdit(self.tab_generalSettings)
        self.lineEdit_prediction4.setObjectName("lineEdit_prediction4")
        self.horizontalLayout_12.addWidget(self.lineEdit_prediction4)
        self.lineEdit_prediction5 = QtWidgets.QLineEdit(self.tab_generalSettings)
        self.lineEdit_prediction5.setObjectName("lineEdit_prediction5")
        self.horizontalLayout_12.addWidget(self.lineEdit_prediction5)
        self.lineEdit_prediction6 = QtWidgets.QLineEdit(self.tab_generalSettings)
        self.lineEdit_prediction6.setObjectName("lineEdit_prediction6")
        self.horizontalLayout_12.addWidget(self.lineEdit_prediction6)
        self.lineEdit_prediction9 = QtWidgets.QLineEdit(self.tab_generalSettings)
        self.lineEdit_prediction9.setObjectName("lineEdit_prediction9")
        self.horizontalLayout_12.addWidget(self.lineEdit_prediction9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_generalSettings, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 701, 299))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.verticalLayoutWidget_2)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_9.addWidget(self.line_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName("formLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalSlider_cycleCount = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.horizontalSlider_cycleCount.setMinimum(1)
        self.horizontalSlider_cycleCount.setMaximum(5)
        self.horizontalSlider_cycleCount.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_cycleCount.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_cycleCount.setTickInterval(1)
        self.horizontalSlider_cycleCount.setObjectName("horizontalSlider_cycleCount")
        self.horizontalLayout_3.addWidget(self.horizontalSlider_cycleCount)
        self.label_cycleCountCounter = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_cycleCountCounter.setObjectName("label_cycleCountCounter")
        self.horizontalLayout_3.addWidget(self.label_cycleCountCounter)
        self.formLayout_5.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_3)
        self.label_cycleCount = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_cycleCount.setObjectName("label_cycleCount")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_cycleCount)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalSlider_interval = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.horizontalSlider_interval.setMinimum(500)
        self.horizontalSlider_interval.setMaximum(5000)
        self.horizontalSlider_interval.setSingleStep(500)
        self.horizontalSlider_interval.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_interval.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_interval.setTickInterval(500)
        self.horizontalSlider_interval.setObjectName("horizontalSlider_interval")
        self.horizontalLayout_4.addWidget(self.horizontalSlider_interval)
        self.label_intervalCounter = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_intervalCounter.setObjectName("label_intervalCounter")
        self.horizontalLayout_4.addWidget(self.label_intervalCounter)
        self.formLayout_5.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_4)
        self.label_interval = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_interval.setObjectName("label_interval")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_interval)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalSlider_startUpLag = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.horizontalSlider_startUpLag.setMaximum(5000)
        self.horizontalSlider_startUpLag.setSingleStep(500)
        self.horizontalSlider_startUpLag.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_startUpLag.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_startUpLag.setTickInterval(500)
        self.horizontalSlider_startUpLag.setObjectName("horizontalSlider_startUpLag")
        self.horizontalLayout_5.addWidget(self.horizontalSlider_startUpLag)
        self.label_startUpLagCounter = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_startUpLagCounter.setObjectName("label_startUpLagCounter")
        self.horizontalLayout_5.addWidget(self.label_startUpLagCounter)
        self.formLayout_5.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_5)
        self.label_startUpLag = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_startUpLag.setObjectName("label_startUpLag")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_startUpLag)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalSlider_selectLag = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.horizontalSlider_selectLag.setMaximum(5000)
        self.horizontalSlider_selectLag.setSingleStep(500)
        self.horizontalSlider_selectLag.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_selectLag.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_selectLag.setTickInterval(500)
        self.horizontalSlider_selectLag.setObjectName("horizontalSlider_selectLag")
        self.horizontalLayout_6.addWidget(self.horizontalSlider_selectLag)
        self.label_selectLagCounter = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_selectLagCounter.sizePolicy().hasHeightForWidth())
        self.label_selectLagCounter.setSizePolicy(sizePolicy)
        self.label_selectLagCounter.setObjectName("label_selectLagCounter")
        self.horizontalLayout_6.addWidget(self.label_selectLagCounter)
        self.formLayout_5.setLayout(3, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_6)
        self.label_selectLag = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_selectLag.setObjectName("label_selectLag")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_selectLag)
        self.comboBox_reactOn = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_reactOn.setObjectName("comboBox_reactOn")
        self.comboBox_reactOn.addItem("")
        self.comboBox_reactOn.addItem("")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.comboBox_reactOn)
        self.label_reactOn = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_reactOn.setObjectName("label_reactOn")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_reactOn)
        self.comboBox_scanSound = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_scanSound.setEditable(True)
        self.comboBox_scanSound.setObjectName("comboBox_scanSound")
        self.comboBox_scanSound.addItem("")
        self.comboBox_scanSound.setItemText(0, "")
        self.comboBox_scanSound.addItem("")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.comboBox_scanSound)
        self.label_scanSound = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_scanSound.setObjectName("label_scanSound")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_scanSound)
        self.horizontalLayout_9.addLayout(self.formLayout_5)
        self.tabWidget.addTab(self.tab, "")
        self.tab_blogSettings = QtWidgets.QWidget()
        self.tab_blogSettings.setObjectName("tab_blogSettings")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab_blogSettings)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 10, 804, 320))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.line_9 = QtWidgets.QFrame(self.horizontalLayoutWidget_3)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_5.addWidget(self.line_9)
        self.label_blogTest = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_blogTest.setWordWrap(True)
        self.label_blogTest.setObjectName("label_blogTest")
        self.verticalLayout_5.addWidget(self.label_blogTest)
        self.horizontalLayout_11.addLayout(self.verticalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.line_7 = QtWidgets.QFrame(self.horizontalLayoutWidget_3)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_11.addWidget(self.line_7)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lineEdit_blogUsername = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_blogUsername.setObjectName("lineEdit_blogUsername")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lineEdit_blogUsername)
        self.label_blogUsername = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_blogUsername.setObjectName("label_blogUsername")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_blogUsername)
        self.lineEdit_blogPassword = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_blogPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_blogPassword.setObjectName("lineEdit_blogPassword")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lineEdit_blogPassword)
        self.label_blogPassword = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_blogPassword.setObjectName("label_blogPassword")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_blogPassword)
        self.lineEdit_blogURL = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_blogURL.setObjectName("lineEdit_blogURL")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lineEdit_blogURL)
        self.label_blogURL = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_blogURL.setObjectName("label_blogURL")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_blogURL)
        self.lineEdit_blogTitle = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_blogTitle.setObjectName("lineEdit_blogTitle")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lineEdit_blogTitle)
        self.label_blogTitle = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_blogTitle.setObjectName("label_blogTitle")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_blogTitle)
        self.pushButton_blogTest = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_blogTest.setObjectName("pushButton_blogTest")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pushButton_blogTest)
        self.verticalLayout_4.addLayout(self.formLayout_2)
        self.line_4 = QtWidgets.QFrame(self.horizontalLayoutWidget_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_4.addWidget(self.line_4)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.scrollArea_followedBlogs = QtWidgets.QScrollArea(self.horizontalLayoutWidget_3)
        self.scrollArea_followedBlogs.setWidgetResizable(True)
        self.scrollArea_followedBlogs.setObjectName("scrollArea_followedBlogs")
        self.scrollAreaWidgetContents_followedBlogs = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_followedBlogs.setGeometry(QtCore.QRect(0, 0, 356, 78))
        self.scrollAreaWidgetContents_followedBlogs.setObjectName("scrollAreaWidgetContents_followedBlogs")
        self.gridLayout_followedBlogs = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_followedBlogs)
        self.gridLayout_followedBlogs.setObjectName("gridLayout_followedBlogs")
        self.scrollArea_followedBlogs.setWidget(self.scrollAreaWidgetContents_followedBlogs)
        self.verticalLayout_4.addWidget(self.scrollArea_followedBlogs)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem5 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.pushButton_addFollowedBlog = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_addFollowedBlog.setMinimumSize(QtCore.QSize(290, 0))
        self.pushButton_addFollowedBlog.setObjectName("pushButton_addFollowedBlog")
        self.horizontalLayout_13.addWidget(self.pushButton_addFollowedBlog)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_11.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab_blogSettings, "")
        self.tab_emailSettings = QtWidgets.QWidget()
        self.tab_emailSettings.setObjectName("tab_emailSettings")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_emailSettings)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 711, 291))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.line_10 = QtWidgets.QFrame(self.horizontalLayoutWidget_2)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_7.addWidget(self.line_10)
        self.label_emailTest = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_emailTest.setText("")
        self.label_emailTest.setWordWrap(True)
        self.label_emailTest.setObjectName("label_emailTest")
        self.verticalLayout_7.addWidget(self.label_emailTest)
        self.horizontalLayout_10.addLayout(self.verticalLayout_7)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.line_6 = QtWidgets.QFrame(self.horizontalLayoutWidget_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_10.addWidget(self.line_6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.lineEdit_emailAddress = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_emailAddress.setObjectName("lineEdit_emailAddress")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lineEdit_emailAddress)
        self.label_emailAddress = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_emailAddress.setObjectName("label_emailAddress")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_emailAddress)
        self.lineEdit_emailPassword = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_emailPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_emailPassword.setObjectName("lineEdit_emailPassword")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lineEdit_emailPassword)
        self.label_emailPassword = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_emailPassword.setObjectName("label_emailPassword")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_emailPassword)
        self.lineEdit_emailSentFolder = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_emailSentFolder.setObjectName("lineEdit_emailSentFolder")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lineEdit_emailSentFolder)
        self.label_emailSentFolder = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_emailSentFolder.setObjectName("label_emailSentFolder")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_emailSentFolder)
        self.lineEdit_emailIMAPServer = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_emailIMAPServer.setObjectName("lineEdit_emailIMAPServer")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lineEdit_emailIMAPServer)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.comboBox_emailPortIMAP = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_emailPortIMAP.setEditable(True)
        self.comboBox_emailPortIMAP.setObjectName("comboBox_emailPortIMAP")
        self.comboBox_emailPortIMAP.addItem("")
        self.comboBox_emailPortIMAP.addItem("")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.comboBox_emailPortIMAP)
        self.label_emailPortIMAP = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_emailPortIMAP.setObjectName("label_emailPortIMAP")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_emailPortIMAP)
        self.lineEdit_emailSMTPServer = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_emailSMTPServer.setObjectName("lineEdit_emailSMTPServer")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lineEdit_emailSMTPServer)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.comboBox_emailPortSMTP = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_emailPortSMTP.setEditable(True)
        self.comboBox_emailPortSMTP.setObjectName("comboBox_emailPortSMTP")
        self.comboBox_emailPortSMTP.addItem("")
        self.comboBox_emailPortSMTP.addItem("")
        self.comboBox_emailPortSMTP.addItem("")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.comboBox_emailPortSMTP)
        self.label_emailPortSMTP = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_emailPortSMTP.setObjectName("label_emailPortSMTP")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.label_emailPortSMTP)
        self.pushButton_emailTest = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_emailTest.setObjectName("pushButton_emailTest")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.pushButton_emailTest)
        self.horizontalLayout_10.addLayout(self.formLayout_3)
        self.tabWidget.addTab(self.tab_emailSettings, "")
        self.tab_spellerSettings = QtWidgets.QWidget()
        self.tab_spellerSettings.setObjectName("tab_spellerSettings")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_spellerSettings)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(40, 20, 521, 271))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_6.addWidget(self.line_5)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem9)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.comboBox_spellerLayout = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.comboBox_spellerLayout.setObjectName("comboBox_spellerLayout")
        self.comboBox_spellerLayout.addItem("")
        self.comboBox_spellerLayout.addItem("")
        self.comboBox_spellerLayout.addItem("")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.comboBox_spellerLayout)
        self.label_spellerLayout = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_spellerLayout.setObjectName("label_spellerLayout")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_spellerLayout)
        self.verticalLayout_6.addLayout(self.formLayout_4)
        self.tabWidget.addTab(self.tab_spellerSettings, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 905, 25))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        self.comboBox_skin.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_abort.setText(_translate("MainWindow", "Anuluj"))
        self.pushButton_apply.setText(_translate("MainWindow", "Zastosuj"))
        self.pushButton_ok.setText(_translate("MainWindow", "Ok"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p>Tutaj możesz wybrać aplikacje, które będą dostępne z poziomu menu głównego.</p></body></html>"))
        self.label_availableApps.setText(_translate("MainWindow", "Dostępne aplikacje"))
        self.checkBox_symboler.setText(_translate("MainWindow", "komunikator symboliczny"))
        self.checkBox_movie.setText(_translate("MainWindow", "odtwarzacz filmów"))
        self.checkBox_audio.setText(_translate("MainWindow", "odtwarzacz muzyki"))
        self.checkBox_viewer.setText(_translate("MainWindow", "przeglądarka zdjęć"))
        self.checkBox_speller.setText(_translate("MainWindow", "edytor tekstu"))
        self.checkBox_email.setText(_translate("MainWindow", "poczta e-mail"))
        self.checkBox_paint.setText(_translate("MainWindow", "rysowanie"))
        self.checkBox_blog.setText(_translate("MainWindow", "blog"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_selectApps), _translate("MainWindow", "Wybór aplikacji"))
        self.comboBox_input.setItemText(0, _translate("MainWindow", "przycisk"))
        self.comboBox_input.setItemText(1, _translate("MainWindow", "przycisk PISAK"))
        self.comboBox_input.setItemText(2, _translate("MainWindow", "okulograf"))
        self.comboBox_input.setItemText(3, _translate("MainWindow", "tobii"))
        self.comboBox_input.setItemText(4, _translate("MainWindow", "eviacam"))
        self.comboBox_input.setItemText(5, _translate("MainWindow", "myszka"))
        self.comboBox_input.setItemText(6, _translate("MainWindow", "okulograf bez korekcji"))
        self.comboBox_input.setItemText(7, _translate("MainWindow", "okulograf testowy"))
        self.comboBox_input.setItemText(8, _translate("MainWindow", "klawiatura (spacja)"))
        self.label_input.setText(_translate("MainWindow", "Urządzenie wejściowe"))
        self.comboBox_skin.setCurrentText(_translate("MainWindow", "domyślna"))
        self.comboBox_skin.setItemText(0, _translate("MainWindow", "domyślna"))
        self.comboBox_skin.setItemText(1, _translate("MainWindow", "turkusowa"))
        self.label_skin.setText(_translate("MainWindow", "Skórka"))
        self.label_volumeCounter.setText(_translate("MainWindow", "0"))
        self.label_volume.setText(_translate("MainWindow", "Głośność dźwięków (%)"))
        self.label_spriteTimeoutCounter.setText(_translate("MainWindow", "0"))
        self.label_spriteTimeout.setText(_translate("MainWindow", "Opóźnienie działania kursora (sek)"))
        self.comboBox_selectSound.setItemText(1, _translate("MainWindow", "selection.wav"))
        self.label_selectSound.setText(_translate("MainWindow", "Dźwięk wyboru"))
        self.checkBox_sounds.setText(_translate("MainWindow", "Odtwarzanie dźwięków"))
        self.checkBox_buttonSoundSupport.setText(_translate("MainWindow", "Wsparcie dźwiękowe dla przycisków"))
        self.checkBox_textCase.setText(_translate("MainWindow", "Litery drukowane"))
        self.label_prediction.setText(_translate("MainWindow", "Domyślna lista słów predykcji:"))
        self.lineEdit_prediction7.setText(_translate("MainWindow", "Chciałbym"))
        self.lineEdit_prediction1.setText(_translate("MainWindow", "Czy"))
        self.lineEdit_prediction8.setText(_translate("MainWindow", "Jak"))
        self.lineEdit_prediction2.setText(_translate("MainWindow", "Jestem"))
        self.lineEdit_prediction3.setText(_translate("MainWindow", "Nie"))
        self.lineEdit_prediction4.setText(_translate("MainWindow", "Niestety"))
        self.lineEdit_prediction5.setText(_translate("MainWindow", "Rzeczywiście"))
        self.lineEdit_prediction6.setText(_translate("MainWindow", "Super"))
        self.lineEdit_prediction9.setText(_translate("MainWindow", "Witam"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_generalSettings), _translate("MainWindow", "Ustawienia ogólne"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>Tutaj możesz dostosować parametry skanowania. Ustawienia odniosą efekt tylko w przypadku gdy włączony zostanie tryb obsługi progamu za pomocą skanowania.</p></body></html>"))
        self.label_cycleCountCounter.setText(_translate("MainWindow", "0"))
        self.label_cycleCount.setText(_translate("MainWindow", "Liczba cykli skanowania"))
        self.label_intervalCounter.setText(_translate("MainWindow", "0"))
        self.label_interval.setText(_translate("MainWindow", "Interwał skanowania (sek)"))
        self.label_startUpLagCounter.setText(_translate("MainWindow", "0"))
        self.label_startUpLag.setText(_translate("MainWindow", "Opóźnienie startu skanowania (sek)"))
        self.label_selectLagCounter.setText(_translate("MainWindow", "0"))
        self.label_selectLag.setText(_translate("MainWindow", "Opóźnienie wykonania czynności po wyborze (sek)"))
        self.comboBox_reactOn.setItemText(0, _translate("MainWindow", "wciśnięcie"))
        self.comboBox_reactOn.setItemText(1, _translate("MainWindow", "odpuszczenie"))
        self.label_reactOn.setText(_translate("MainWindow", "Reakcja przycisku na"))
        self.comboBox_scanSound.setItemText(1, _translate("MainWindow", "scan.wav"))
        self.label_scanSound.setText(_translate("MainWindow", "Dźwięk skanowania"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Skanowanie"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>Podaj ustawienia swojego bloga, a następnie wciśnij przycisk &quot;Testuj połączenie&quot; aby sprawdzić poprawność wpisanych danych i stan połączenia z serwerem.</p><p>Jeśli nie masz jeszcze swojego bloga, a chciałbyś go założyć, skontaktuj się z obsługą techniczną projektu PISAK.</p><p>Możesz także podać adresy inych blogów, które chcesz śledzić i przeglądać w ramach aplikacji.</p></body></html>"))
        self.label_blogTest.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_blogUsername.setText(_translate("MainWindow", "Nazwa użytkownika"))
        self.label_blogPassword.setText(_translate("MainWindow", "Hasło"))
        self.label_blogURL.setText(_translate("MainWindow", "Adres URL bloga"))
        self.label_blogTitle.setText(_translate("MainWindow", "Tytuł bloga"))
        self.pushButton_blogTest.setText(_translate("MainWindow", "Testuj połączenie"))
        self.label.setText(_translate("MainWindow", "Śledzone blogi:"))
        self.pushButton_addFollowedBlog.setText(_translate("MainWindow", "Dodaj blog"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_blogSettings), _translate("MainWindow", "Blog"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>Wypełnij ustawienia skrzynki e-mail, a następnie wciśnij przycisk &quot;Testuj połączenie&quot; aby nawiązać połączenie z serwerem pocztowym i sprawdzić podaną konfigurację.</p><p>Serwer IMAP to serwer poczty przychodzącej, a serwer SMTP to serwer poczty wychodzącej.</p></body></html>"))
        self.label_emailAddress.setText(_translate("MainWindow", "Adres e-mail"))
        self.label_emailPassword.setText(_translate("MainWindow", "Hasło"))
        self.label_emailSentFolder.setText(_translate("MainWindow", "Folder wysłanych"))
        self.label_2.setText(_translate("MainWindow", "Adres serwera IMAP"))
        self.comboBox_emailPortIMAP.setItemText(0, _translate("MainWindow", "993"))
        self.comboBox_emailPortIMAP.setItemText(1, _translate("MainWindow", "143"))
        self.label_emailPortIMAP.setText(_translate("MainWindow", "Port serwera IMAP"))
        self.label_3.setText(_translate("MainWindow", "Adres serwera SMTP"))
        self.comboBox_emailPortSMTP.setItemText(0, _translate("MainWindow", "465"))
        self.comboBox_emailPortSMTP.setItemText(1, _translate("MainWindow", "587"))
        self.comboBox_emailPortSMTP.setItemText(2, _translate("MainWindow", "25"))
        self.label_emailPortSMTP.setText(_translate("MainWindow", "Port serwera SMTP"))
        self.pushButton_emailTest.setText(_translate("MainWindow", "Testuj połączenie"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_emailSettings), _translate("MainWindow", "Poczta e-mail"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p>Domyślny układ klawiatury to tzw. układ QWERTY, odpowiadający rozłożeniu przycisków na standardowej klawiaturze komputerowej.</p><p>W przypadku układu alfabetycznego klawisze są ułożone alfabetycznie, tzn. w przypadku użycia systemu skanowania czas dojścia do pola z literą &quot;a&quot; jest najkrótszy, a do pola z literą &quot;z&quot; najdłuższy.</p><p>Układ częstotliwościowy segreguje litery zgodnie z częstością ich występowania w języku polskim.</p></body></html>"))
        self.comboBox_spellerLayout.setItemText(0, _translate("MainWindow", "domyślny"))
        self.comboBox_spellerLayout.setItemText(1, _translate("MainWindow", "alfabetyczny"))
        self.comboBox_spellerLayout.setItemText(2, _translate("MainWindow", "częstotliwościowy"))
        self.label_spellerLayout.setText(_translate("MainWindow", "Układ klawiatury"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_spellerSettings), _translate("MainWindow", "Edytor tekstu"))

