# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'panel.ui'
#
# Created: Wed Oct  7 15:45:29 2015
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(905, 708)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, -10, 851, 601))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_selectApps = QtWidgets.QWidget()
        self.tab_selectApps.setObjectName("tab_selectApps")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_selectApps)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(160, 70, 221, 245))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_availableApps = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_availableApps.setFont(font)
        self.label_availableApps.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_availableApps.setAlignment(QtCore.Qt.AlignCenter)
        self.label_availableApps.setObjectName("label_availableApps")
        self.verticalLayout.addWidget(self.label_availableApps)
        self.checkBox_symboler = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_symboler.setObjectName("checkBox_symboler")
        self.verticalLayout.addWidget(self.checkBox_symboler)
        self.checkBox_movie = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_movie.setObjectName("checkBox_movie")
        self.verticalLayout.addWidget(self.checkBox_movie)
        self.checkBox_audio = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_audio.setObjectName("checkBox_audio")
        self.verticalLayout.addWidget(self.checkBox_audio)
        self.checkBox_viewer = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_viewer.setObjectName("checkBox_viewer")
        self.verticalLayout.addWidget(self.checkBox_viewer)
        self.checkBox_speller = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_speller.setObjectName("checkBox_speller")
        self.verticalLayout.addWidget(self.checkBox_speller)
        self.checkBox_email = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_email.setObjectName("checkBox_email")
        self.verticalLayout.addWidget(self.checkBox_email)
        self.checkBox_paint = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_paint.setObjectName("checkBox_paint")
        self.verticalLayout.addWidget(self.checkBox_paint)
        self.checkBox_blog = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_blog.setObjectName("checkBox_blog")
        self.verticalLayout.addWidget(self.checkBox_blog)
        self.tabWidget.addTab(self.tab_selectApps, "")
        self.tab_generalSettings = QtWidgets.QWidget()
        self.tab_generalSettings.setObjectName("tab_generalSettings")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_generalSettings)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 831, 562))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.comboBox_input = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_input.setObjectName("comboBox_input")
        self.comboBox_input.addItem("")
        self.comboBox_input.addItem("")
        self.comboBox_input.addItem("")
        self.comboBox_input.addItem("")
        self.comboBox_input.addItem("")
        self.comboBox_input.addItem("")
        self.comboBox_input.addItem("")
        self.comboBox_input.addItem("")
        self.comboBox_input.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.comboBox_input)
        self.label_input = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_input.setObjectName("label_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_input)
        self.comboBox_skin = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_skin.setEditable(False)
        self.comboBox_skin.setObjectName("comboBox_skin")
        self.comboBox_skin.addItem("")
        self.comboBox_skin.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.comboBox_skin)
        self.label_skin = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_skin.setObjectName("label_skin")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_skin)
        self.horizontalSlider_volume = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.horizontalSlider_volume.setMaximum(100)
        self.horizontalSlider_volume.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_volume.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_volume.setTickInterval(10)
        self.horizontalSlider_volume.setObjectName("horizontalSlider_volume")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.horizontalSlider_volume)
        self.label_volume = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_volume.setObjectName("label_volume")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_volume)
        self.checkBox_sounds = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_sounds.setObjectName("checkBox_sounds")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.checkBox_sounds)
        self.checkBox_buttonSoundSupport = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_buttonSoundSupport.setObjectName("checkBox_buttonSoundSupport")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.checkBox_buttonSoundSupport)
        self.checkBox_textCase = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_textCase.setObjectName("checkBox_textCase")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.checkBox_textCase)
        self.label_cycleCount = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_cycleCount.setObjectName("label_cycleCount")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.label_cycleCount)
        self.label_interval = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_interval.setObjectName("label_interval")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.label_interval)
        self.label_startUpLag = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_startUpLag.setObjectName("label_startUpLag")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.label_startUpLag)
        self.label_selectLag = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_selectLag.setObjectName("label_selectLag")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.label_selectLag)
        self.label_spriteTimeout = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_spriteTimeout.setObjectName("label_spriteTimeout")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.label_spriteTimeout)
        self.comboBox_reactOn = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_reactOn.setObjectName("comboBox_reactOn")
        self.comboBox_reactOn.addItem("")
        self.comboBox_reactOn.addItem("")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.comboBox_reactOn)
        self.label_reactOn = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_reactOn.setObjectName("label_reactOn")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.label_reactOn)
        self.comboBox_selectSound = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_selectSound.setEditable(True)
        self.comboBox_selectSound.setObjectName("comboBox_selectSound")
        self.comboBox_selectSound.addItem("")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.comboBox_selectSound)
        self.label_selectSound = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_selectSound.setObjectName("label_selectSound")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.label_selectSound)
        self.comboBox_scanSound = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_scanSound.setEditable(True)
        self.comboBox_scanSound.setObjectName("comboBox_scanSound")
        self.comboBox_scanSound.addItem("")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.comboBox_scanSound)
        self.label_scanSound = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_scanSound.setObjectName("label_scanSound")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.label_scanSound)
        self.horizontalSlider_cycleCount = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.horizontalSlider_cycleCount.setMinimum(1)
        self.horizontalSlider_cycleCount.setMaximum(5)
        self.horizontalSlider_cycleCount.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_cycleCount.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_cycleCount.setTickInterval(1)
        self.horizontalSlider_cycleCount.setObjectName("horizontalSlider_cycleCount")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.horizontalSlider_cycleCount)
        self.horizontalSlider_interval = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.horizontalSlider_interval.setMinimum(500)
        self.horizontalSlider_interval.setMaximum(5000)
        self.horizontalSlider_interval.setSingleStep(500)
        self.horizontalSlider_interval.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_interval.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_interval.setTickInterval(500)
        self.horizontalSlider_interval.setObjectName("horizontalSlider_interval")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.horizontalSlider_interval)
        self.horizontalSlider_selectLag = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.horizontalSlider_selectLag.setMaximum(5)
        self.horizontalSlider_selectLag.setSingleStep(1)
        self.horizontalSlider_selectLag.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_selectLag.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_selectLag.setTickInterval(1)
        self.horizontalSlider_selectLag.setObjectName("horizontalSlider_selectLag")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.horizontalSlider_selectLag)
        self.horizontalSlider_startUpLag = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.horizontalSlider_startUpLag.setMaximum(5)
        self.horizontalSlider_startUpLag.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_startUpLag.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_startUpLag.setTickInterval(1)
        self.horizontalSlider_startUpLag.setObjectName("horizontalSlider_startUpLag")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.horizontalSlider_startUpLag)
        self.horizontalSlider_spriteTimeout = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.horizontalSlider_spriteTimeout.setMinimum(500)
        self.horizontalSlider_spriteTimeout.setMaximum(5000)
        self.horizontalSlider_spriteTimeout.setSingleStep(500)
        self.horizontalSlider_spriteTimeout.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_spriteTimeout.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_spriteTimeout.setTickInterval(500)
        self.horizontalSlider_spriteTimeout.setObjectName("horizontalSlider_spriteTimeout")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.horizontalSlider_spriteTimeout)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.label_prediction = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_prediction.setObjectName("label_prediction")
        self.verticalLayout_3.addWidget(self.label_prediction)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lineEdit_prediction7 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_prediction7.setObjectName("lineEdit_prediction7")
        self.horizontalLayout_12.addWidget(self.lineEdit_prediction7)
        self.lineEdit_prediction1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_prediction1.setObjectName("lineEdit_prediction1")
        self.horizontalLayout_12.addWidget(self.lineEdit_prediction1)
        self.lineEdit_prediction8 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_prediction8.setObjectName("lineEdit_prediction8")
        self.horizontalLayout_12.addWidget(self.lineEdit_prediction8)
        self.lineEdit_prediction2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_prediction2.setObjectName("lineEdit_prediction2")
        self.horizontalLayout_12.addWidget(self.lineEdit_prediction2)
        self.lineEdit_prediction3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_prediction3.setObjectName("lineEdit_prediction3")
        self.horizontalLayout_12.addWidget(self.lineEdit_prediction3)
        self.lineEdit_prediction4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_prediction4.setObjectName("lineEdit_prediction4")
        self.horizontalLayout_12.addWidget(self.lineEdit_prediction4)
        self.lineEdit_prediction5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_prediction5.setObjectName("lineEdit_prediction5")
        self.horizontalLayout_12.addWidget(self.lineEdit_prediction5)
        self.lineEdit_prediction6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_prediction6.setObjectName("lineEdit_prediction6")
        self.horizontalLayout_12.addWidget(self.lineEdit_prediction6)
        self.lineEdit_prediction9 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_prediction9.setObjectName("lineEdit_prediction9")
        self.horizontalLayout_12.addWidget(self.lineEdit_prediction9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab_generalSettings, "")
        self.tab_blogSettings = QtWidgets.QWidget()
        self.tab_blogSettings.setObjectName("tab_blogSettings")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_blogSettings)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 741, 311))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lineEdit_blogUsername = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_blogUsername.setObjectName("lineEdit_blogUsername")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lineEdit_blogUsername)
        self.label_blogUsername = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_blogUsername.setObjectName("label_blogUsername")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_blogUsername)
        self.lineEdit_blogPassword = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_blogPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_blogPassword.setObjectName("lineEdit_blogPassword")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lineEdit_blogPassword)
        self.label_blogPassword = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_blogPassword.setObjectName("label_blogPassword")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_blogPassword)
        self.lineEdit_blogURL = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_blogURL.setObjectName("lineEdit_blogURL")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lineEdit_blogURL)
        self.label_blogURL = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_blogURL.setObjectName("label_blogURL")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_blogURL)
        self.lineEdit_blogTitle = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_blogTitle.setObjectName("lineEdit_blogTitle")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lineEdit_blogTitle)
        self.label_blogTitle = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_blogTitle.setObjectName("label_blogTitle")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_blogTitle)
        self.pushButton_blogTest = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_blogTest.setObjectName("pushButton_blogTest")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pushButton_blogTest)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.formLayout_10 = QtWidgets.QFormLayout()
        self.formLayout_10.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_10.setObjectName("formLayout_10")
        self.comboBox_blogLayout = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.comboBox_blogLayout.setObjectName("comboBox_blogLayout")
        self.comboBox_blogLayout.addItem("")
        self.comboBox_blogLayout.addItem("")
        self.comboBox_blogLayout.addItem("")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.comboBox_blogLayout)
        self.label_blogLayout = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_blogLayout.setObjectName("label_blogLayout")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_blogLayout)
        self.horizontalLayout.addLayout(self.formLayout_10)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_4.addWidget(self.line_4)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.lineEdit_followedBlog1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_followedBlog1.setObjectName("lineEdit_followedBlog1")
        self.verticalLayout_4.addWidget(self.lineEdit_followedBlog1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab_blogSettings, "")
        self.tab_emailSettings = QtWidgets.QWidget()
        self.tab_emailSettings.setObjectName("tab_emailSettings")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_emailSettings)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 90, 821, 285))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.lineEdit_emailAddress = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_emailAddress.setObjectName("lineEdit_emailAddress")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lineEdit_emailAddress)
        self.label_emailAddress = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_emailAddress.setObjectName("label_emailAddress")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_emailAddress)
        self.lineEdit_emailPassword = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_emailPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_emailPassword.setObjectName("lineEdit_emailPassword")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lineEdit_emailPassword)
        self.label_emailPassword = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_emailPassword.setObjectName("label_emailPassword")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_emailPassword)
        self.comboBox_emailPortSMTP = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_emailPortSMTP.setEditable(True)
        self.comboBox_emailPortSMTP.setObjectName("comboBox_emailPortSMTP")
        self.comboBox_emailPortSMTP.addItem("")
        self.comboBox_emailPortSMTP.addItem("")
        self.comboBox_emailPortSMTP.addItem("")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.comboBox_emailPortSMTP)
        self.label_emailPortSMTP = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_emailPortSMTP.setObjectName("label_emailPortSMTP")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.label_emailPortSMTP)
        self.pushButton_emailTest = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_emailTest.setObjectName("pushButton_emailTest")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.pushButton_emailTest)
        self.label_emailSentFolder = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_emailSentFolder.setObjectName("label_emailSentFolder")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_emailSentFolder)
        self.lineEdit_emailSentFolder = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_emailSentFolder.setObjectName("lineEdit_emailSentFolder")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lineEdit_emailSentFolder)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.lineEdit_emailIMAPServer = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_emailIMAPServer.setObjectName("lineEdit_emailIMAPServer")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lineEdit_emailIMAPServer)
        self.lineEdit_emailSMTPServer = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_emailSMTPServer.setObjectName("lineEdit_emailSMTPServer")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lineEdit_emailSMTPServer)
        self.label_emailPortIMAP = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_emailPortIMAP.setObjectName("label_emailPortIMAP")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_emailPortIMAP)
        self.comboBox_emailPortIMAP = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_emailPortIMAP.setEditable(True)
        self.comboBox_emailPortIMAP.setObjectName("comboBox_emailPortIMAP")
        self.comboBox_emailPortIMAP.addItem("")
        self.comboBox_emailPortIMAP.addItem("")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.comboBox_emailPortIMAP)
        self.horizontalLayout_2.addLayout(self.formLayout_3)
        self.line_3 = QtWidgets.QFrame(self.horizontalLayoutWidget_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        self.formLayout_11 = QtWidgets.QFormLayout()
        self.formLayout_11.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_11.setObjectName("formLayout_11")
        self.comboBox_emailLayout = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_emailLayout.setObjectName("comboBox_emailLayout")
        self.comboBox_emailLayout.addItem("")
        self.comboBox_emailLayout.addItem("")
        self.comboBox_emailLayout.addItem("")
        self.formLayout_11.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.comboBox_emailLayout)
        self.label_emailLayout = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_emailLayout.setObjectName("label_emailLayout")
        self.formLayout_11.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_emailLayout)
        self.horizontalLayout_2.addLayout(self.formLayout_11)
        self.tabWidget.addTab(self.tab_emailSettings, "")
        self.tab_spellerSettings = QtWidgets.QWidget()
        self.tab_spellerSettings.setObjectName("tab_spellerSettings")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.tab_spellerSettings)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(130, 50, 372, 118))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.comboBox_spellerLayout = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.comboBox_spellerLayout.setObjectName("comboBox_spellerLayout")
        self.comboBox_spellerLayout.addItem("")
        self.comboBox_spellerLayout.addItem("")
        self.comboBox_spellerLayout.addItem("")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.comboBox_spellerLayout)
        self.label_spellerLayout = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_spellerLayout.setObjectName("label_spellerLayout")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_spellerLayout)
        self.tabWidget.addTab(self.tab_spellerSettings, "")
        self.tab_symbolerSettings = QtWidgets.QWidget()
        self.tab_symbolerSettings.setObjectName("tab_symbolerSettings")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.tab_symbolerSettings)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(80, 50, 381, 118))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.comboBox_symbolerLayout = QtWidgets.QComboBox(self.formLayoutWidget_5)
        self.comboBox_symbolerLayout.setObjectName("comboBox_symbolerLayout")
        self.comboBox_symbolerLayout.addItem("")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.comboBox_symbolerLayout)
        self.label_symbolerLayout = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_symbolerLayout.setObjectName("label_symbolerLayout")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_symbolerLayout)
        self.tabWidget.addTab(self.tab_symbolerSettings, "")
        self.tab_audioSettings = QtWidgets.QWidget()
        self.tab_audioSettings.setObjectName("tab_audioSettings")
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.tab_audioSettings)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(120, 70, 372, 118))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_6.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.comboBox_audioLayout = QtWidgets.QComboBox(self.formLayoutWidget_6)
        self.comboBox_audioLayout.setObjectName("comboBox_audioLayout")
        self.comboBox_audioLayout.addItem("")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.comboBox_audioLayout)
        self.label_audioLayout = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_audioLayout.setObjectName("label_audioLayout")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_audioLayout)
        self.tabWidget.addTab(self.tab_audioSettings, "")
        self.tab_movieSettings = QtWidgets.QWidget()
        self.tab_movieSettings.setObjectName("tab_movieSettings")
        self.formLayoutWidget_7 = QtWidgets.QWidget(self.tab_movieSettings)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(60, 40, 372, 118))
        self.formLayoutWidget_7.setObjectName("formLayoutWidget_7")
        self.formLayout_7 = QtWidgets.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_7.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.comboBox_movieLayout = QtWidgets.QComboBox(self.formLayoutWidget_7)
        self.comboBox_movieLayout.setObjectName("comboBox_movieLayout")
        self.comboBox_movieLayout.addItem("")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.comboBox_movieLayout)
        self.label_movieLayout = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_movieLayout.setObjectName("label_movieLayout")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_movieLayout)
        self.tabWidget.addTab(self.tab_movieSettings, "")
        self.tab_viewerSettings = QtWidgets.QWidget()
        self.tab_viewerSettings.setObjectName("tab_viewerSettings")
        self.formLayoutWidget_8 = QtWidgets.QWidget(self.tab_viewerSettings)
        self.formLayoutWidget_8.setGeometry(QtCore.QRect(80, 60, 372, 118))
        self.formLayoutWidget_8.setObjectName("formLayoutWidget_8")
        self.formLayout_8 = QtWidgets.QFormLayout(self.formLayoutWidget_8)
        self.formLayout_8.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.comboBox_viewerLayout = QtWidgets.QComboBox(self.formLayoutWidget_8)
        self.comboBox_viewerLayout.setObjectName("comboBox_viewerLayout")
        self.comboBox_viewerLayout.addItem("")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.comboBox_viewerLayout)
        self.label_viewerLayout = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_viewerLayout.setObjectName("label_viewerLayout")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_viewerLayout)
        self.tabWidget.addTab(self.tab_viewerSettings, "")
        self.tab_paintSettings = QtWidgets.QWidget()
        self.tab_paintSettings.setObjectName("tab_paintSettings")
        self.formLayoutWidget_9 = QtWidgets.QWidget(self.tab_paintSettings)
        self.formLayoutWidget_9.setGeometry(QtCore.QRect(40, 60, 372, 118))
        self.formLayoutWidget_9.setObjectName("formLayoutWidget_9")
        self.formLayout_9 = QtWidgets.QFormLayout(self.formLayoutWidget_9)
        self.formLayout_9.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_9.setContentsMargins(0, 0, 0, 0)
        self.formLayout_9.setObjectName("formLayout_9")
        self.comboBox_paintLayout = QtWidgets.QComboBox(self.formLayoutWidget_9)
        self.comboBox_paintLayout.setObjectName("comboBox_paintLayout")
        self.comboBox_paintLayout.addItem("")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.comboBox_paintLayout)
        self.label_paintLayout = QtWidgets.QLabel(self.formLayoutWidget_9)
        self.label_paintLayout.setObjectName("label_paintLayout")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_paintLayout)
        self.tabWidget.addTab(self.tab_paintSettings, "")
        self.pushButton_Abort = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Abort.setGeometry(QtCore.QRect(540, 620, 99, 27))
        self.pushButton_Abort.setObjectName("pushButton_Abort")
        self.pushButton_Apply = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Apply.setGeometry(QtCore.QRect(640, 620, 99, 27))
        self.pushButton_Apply.setObjectName("pushButton_Apply")
        self.pushButton_Ok = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Ok.setGeometry(QtCore.QRect(740, 620, 99, 27))
        self.pushButton_Ok.setObjectName("pushButton_Ok")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 905, 25))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.comboBox_skin.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_availableApps.setText(_translate("MainWindow", "Dostępne aplikacje"))
        self.checkBox_symboler.setText(_translate("MainWindow", "komunikator symboliczny"))
        self.checkBox_movie.setText(_translate("MainWindow", "odtwarzacz filmów"))
        self.checkBox_audio.setText(_translate("MainWindow", "odtwarzacz muzyki"))
        self.checkBox_viewer.setText(_translate("MainWindow", "przeglądarka zdjęć"))
        self.checkBox_speller.setText(_translate("MainWindow", "edytor tekstu"))
        self.checkBox_email.setText(_translate("MainWindow", "poczta e-mail"))
        self.checkBox_paint.setText(_translate("MainWindow", "rysowanie"))
        self.checkBox_blog.setText(_translate("MainWindow", "blog"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_selectApps), _translate("MainWindow", "Wybór aplikacji"))
        self.comboBox_input.setItemText(0, _translate("MainWindow", "mouse-switch"))
        self.comboBox_input.setItemText(1, _translate("MainWindow", "pisak-switch"))
        self.comboBox_input.setItemText(2, _translate("MainWindow", "eyetracker"))
        self.comboBox_input.setItemText(3, _translate("MainWindow", "tobii"))
        self.comboBox_input.setItemText(4, _translate("MainWindow", "eviacam"))
        self.comboBox_input.setItemText(5, _translate("MainWindow", "mouse"))
        self.comboBox_input.setItemText(6, _translate("MainWindow", "eyetracker-no-correction"))
        self.comboBox_input.setItemText(7, _translate("MainWindow", "eyetracker-mockup"))
        self.comboBox_input.setItemText(8, _translate("MainWindow", "keyboard"))
        self.label_input.setText(_translate("MainWindow", "Urządzenie wejściowe"))
        self.comboBox_skin.setCurrentText(_translate("MainWindow", "default"))
        self.comboBox_skin.setItemText(0, _translate("MainWindow", "default"))
        self.comboBox_skin.setItemText(1, _translate("MainWindow", "turquoise"))
        self.label_skin.setText(_translate("MainWindow", "Skórka"))
        self.label_volume.setText(_translate("MainWindow", "Głośność dźwięków"))
        self.checkBox_sounds.setText(_translate("MainWindow", "Odtwarzanie dźwięków"))
        self.checkBox_buttonSoundSupport.setText(_translate("MainWindow", "Wsparcie dźwiękowe dla przycisków"))
        self.checkBox_textCase.setText(_translate("MainWindow", "Litery drukowane"))
        self.label_cycleCount.setText(_translate("MainWindow", "Liczba cykli skanowania"))
        self.label_interval.setText(_translate("MainWindow", "Interwał skanowania (sek)"))
        self.label_startUpLag.setText(_translate("MainWindow", "Opóźnienie startu skanowania (sek)"))
        self.label_selectLag.setText(_translate("MainWindow", "Opóźnienie wykonania czynności po kliknięciu (sek)"))
        self.label_spriteTimeout.setText(_translate("MainWindow", "Opóźnienie działania kursora (sek)"))
        self.comboBox_reactOn.setItemText(0, _translate("MainWindow", "wciśnięcie"))
        self.comboBox_reactOn.setItemText(1, _translate("MainWindow", "odpuszczenie"))
        self.label_reactOn.setText(_translate("MainWindow", "Reakcja przycisku na"))
        self.comboBox_selectSound.setItemText(0, _translate("MainWindow", "selection.wav"))
        self.label_selectSound.setText(_translate("MainWindow", "Dźwięk wyboru"))
        self.comboBox_scanSound.setItemText(0, _translate("MainWindow", "scan.wav"))
        self.label_scanSound.setText(_translate("MainWindow", "Dźwięk skanowania"))
        self.label_prediction.setText(_translate("MainWindow", "Domyślna lista słów predykcji:"))
        self.lineEdit_prediction7.setText(_translate("MainWindow", "Chciałbym"))
        self.lineEdit_prediction1.setText(_translate("MainWindow", "Czy"))
        self.lineEdit_prediction8.setText(_translate("MainWindow", "Jak"))
        self.lineEdit_prediction2.setText(_translate("MainWindow", "Jestem"))
        self.lineEdit_prediction3.setText(_translate("MainWindow", "Nie"))
        self.lineEdit_prediction4.setText(_translate("MainWindow", "Niestety"))
        self.lineEdit_prediction5.setText(_translate("MainWindow", "Rzeczywiście"))
        self.lineEdit_prediction6.setText(_translate("MainWindow", "Super"))
        self.lineEdit_prediction9.setText(_translate("MainWindow", "Witam"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_generalSettings), _translate("MainWindow", "Ustawienia ogólne"))
        self.label_blogUsername.setText(_translate("MainWindow", "Nazwa użytkownika"))
        self.label_blogPassword.setText(_translate("MainWindow", "Hasło"))
        self.label_blogURL.setText(_translate("MainWindow", "Adres URL bloga"))
        self.label_blogTitle.setText(_translate("MainWindow", "Tytuł bloga"))
        self.pushButton_blogTest.setText(_translate("MainWindow", "Testuj połączenie"))
        self.comboBox_blogLayout.setItemText(0, _translate("MainWindow", "default"))
        self.comboBox_blogLayout.setItemText(1, _translate("MainWindow", "alphabetical"))
        self.comboBox_blogLayout.setItemText(2, _translate("MainWindow", "frequency"))
        self.label_blogLayout.setText(_translate("MainWindow", "Układ elementów aplikacji"))
        self.label.setText(_translate("MainWindow", "Śledzone blogi:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_blogSettings), _translate("MainWindow", "Blog"))
        self.label_emailAddress.setText(_translate("MainWindow", "Adres e-mail"))
        self.label_emailPassword.setText(_translate("MainWindow", "Hasło"))
        self.comboBox_emailPortSMTP.setItemText(0, _translate("MainWindow", "465"))
        self.comboBox_emailPortSMTP.setItemText(1, _translate("MainWindow", "587"))
        self.comboBox_emailPortSMTP.setItemText(2, _translate("MainWindow", "25"))
        self.label_emailPortSMTP.setText(_translate("MainWindow", "Port serwera SMTP"))
        self.pushButton_emailTest.setText(_translate("MainWindow", "Testuj połączenie"))
        self.label_emailSentFolder.setText(_translate("MainWindow", "Folder wysłanych"))
        self.label_2.setText(_translate("MainWindow", "Adres serwera IMAP"))
        self.label_3.setText(_translate("MainWindow", "Adres serwera SMTP"))
        self.label_emailPortIMAP.setText(_translate("MainWindow", "Port serwera IMAP"))
        self.comboBox_emailPortIMAP.setItemText(0, _translate("MainWindow", "993"))
        self.comboBox_emailPortIMAP.setItemText(1, _translate("MainWindow", "143"))
        self.comboBox_emailLayout.setItemText(0, _translate("MainWindow", "default"))
        self.comboBox_emailLayout.setItemText(1, _translate("MainWindow", "alphabetical"))
        self.comboBox_emailLayout.setItemText(2, _translate("MainWindow", "frequency"))
        self.label_emailLayout.setText(_translate("MainWindow", "Układ elementów aplikacji"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_emailSettings), _translate("MainWindow", "Poczta e-mail"))
        self.comboBox_spellerLayout.setItemText(0, _translate("MainWindow", "default"))
        self.comboBox_spellerLayout.setItemText(1, _translate("MainWindow", "alphabetical"))
        self.comboBox_spellerLayout.setItemText(2, _translate("MainWindow", "frequency"))
        self.label_spellerLayout.setText(_translate("MainWindow", "Układ elementów aplikacji"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_spellerSettings), _translate("MainWindow", "Edytor tekstu"))
        self.comboBox_symbolerLayout.setItemText(0, _translate("MainWindow", "default"))
        self.label_symbolerLayout.setText(_translate("MainWindow", "Układ elementów aplikacji"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_symbolerSettings), _translate("MainWindow", "Komunikator symboliczny"))
        self.comboBox_audioLayout.setItemText(0, _translate("MainWindow", "default"))
        self.label_audioLayout.setText(_translate("MainWindow", "Układ elementów aplikacji"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_audioSettings), _translate("MainWindow", "Odtwarzacz muzyki"))
        self.comboBox_movieLayout.setItemText(0, _translate("MainWindow", "default"))
        self.label_movieLayout.setText(_translate("MainWindow", "Układ elementów aplikacji"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_movieSettings), _translate("MainWindow", "Odtwarzacz filmów"))
        self.comboBox_viewerLayout.setItemText(0, _translate("MainWindow", "default"))
        self.label_viewerLayout.setText(_translate("MainWindow", "Układ elementów aplikacji"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_viewerSettings), _translate("MainWindow", "Przeglądarka zdjęć"))
        self.comboBox_paintLayout.setItemText(0, _translate("MainWindow", "default"))
        self.label_paintLayout.setText(_translate("MainWindow", "Układ elementów aplikacji"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_paintSettings), _translate("MainWindow", "Rysowanie"))
        self.pushButton_Abort.setText(_translate("MainWindow", "Anuluj"))
        self.pushButton_Apply.setText(_translate("MainWindow", "Zastosuj"))
        self.pushButton_Ok.setText(_translate("MainWindow", "Ok"))

